server:
  port: 31001

spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cms
  freemarker:
    settings:
      template_update_delay: 0
    cache: false
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    addresses: 127.0.0.1
    virtual-host: /
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
      url: jdbc:mysql://localhost:3306/xc_course?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
      #      url: jdbc:mysql://172.18.54.9:3306/xc_course?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: wangzexu
